### PR TITLE
Minor fix so builds using IDF 5+ will be successful

### PR DESCRIPTION
**Pull request by kbx81**
See https://github.com/esphome/esphome/pull/6802

### CODE REVIEW

**Comment by droscy** [comment]
Hi @kbx81 thanks for your contribution. I'll test and merge asap.

**Comment by kbx81** [comment]
Thank you @droscy! 🍻

**Comment by droscy** [comment]
Hello @kbx81, the code builds but it does not work, I have a stack trace and then a reboot. I tested with esp-idf v5.0.2.
Is this the expected behaviour at the moment?

**Comment by kbx81** [comment]
@droscy I only did a compile test with this change -- I don't have Wireguard set up here right now so I don't have a way to test the running code. That said, I could set it up and troubleshoot further -- it should not crash. Did the stack trace indicate what/where the problem is?

**Comment by kbx81** [comment]
I did some research on this today; there is a workaround for the crash here: https://github.com/trombik/esp_wireguard/issues/33#issuecomment-1568503651

Implementing the workaround in ESPHome requires little more than adding `add_idf_sdkconfig_option("CONFIG_LWIP_PPP_SUPPORT", True)` into the `to_code` function in the Wireguard component's `__init__.py` file (in addition to the patch in this PR).

I have tested this and confirmed that it mitigates the crash in IDF 5+ and that the tunnel still comes up and will transport traffic. 🎉

I also confirmed that this patch has no impact on configurations using ESPHome's current default version of IDF (4.4.7) or Arduino.

I'd like to get this change merged and the library updated so we can begin testing all components in ESPHome against IDF 5. I'm happy to take care of the changes we need to do in ESPHome to take care of adding the extra build flag and version bump. 😄

**Comment by droscy** [comment]
Yes, the error in the stack trace is exactly the issue you pointed out.

I asked only to understand the level of your patch but you made a great job in searching and debugging, really many thanks. Il merge it immediately.

**Comment by kbx81** [comment]
Thank you very much, @droscy! Happy to help. 🍻

**Pull request merged**
